openapi: "3.0.0"

info:
  title: API AppRole
  version: "1.0"
  description: Role API

servers:
  - url: http://localhost:8080/scolarite-mono/api

tags:
  - name: AppRole
    description: AppRole specific data.

paths:
  /appRoles:
    get:
      tags:
        - AppRole
      summary: Get All Actif Role
      operationId: getAllAppRoles
      parameters:
        - name: currentPage
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: sizePage
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: SUCCESS
          content:
            'application/json':
              schema:
                $ref: '../model/appRole/AppRoleResultListDTO.yml'
        '404':
          description: NOT FOUND
        '400':
          description: BAD REQUEST

  /articles-reference:
    get:
      tags:
        - AppRole
      summary: Retrieve an AppRole
      operationId: getAppRole
      parameters:
        - name: idAppRole
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: SUCCESS
          content:
            'application/json':
              schema:
                $ref: '../model/appRole/AppRoleDTO.yml'
        '404':
          description: NOT FOUND
        '400':
          description: BAD REQUEST